Плагин разработан Денисом Тимофеевым:
  Вконтакте: https://vk.com/M0odi
  Telegram: https://t.me/M0odiX

# MySQL
host: localhost
database: M0odiBans
user: root
password: ""

# Период проверки всех игроков на бан в секундах.
# Поставьте на -1, чтобы отключить (если ваши сервера не связаны BungeeCord или Velocity)
delay: 10

# Приоритеты будут работать только в том случае,
# если у всех групп в LuckPerms настроены приоритеты (weight).
# Настройте приоритеты групп в LuckPerms командой /lp group <Название Группы> setWeight <Приоритет>.
# Чем выше группа, тем больше должен быть ее приоритет.
priorities:
  default: 0
  lord: 1
  admin: 2

# Запрещенные для использования команды во время мута.
forbidden-commands:
  - "/m"
  - "/w"
  - "/msg"
  - "/tell"